#!/bin/bash

###checking if the file exists
if [ -e /etc/phonebook/phonebookDB.txt ]
	then
	echo "$USER's DATABASE ready"
else	
	touch /etc/phonebook/phonebookDB.txt
	chmod u+rx /etc/phonebook/phonebookDB.txt
fi

###reading the file
DB="/etc/phonebook/phonebookDB.txt"


###reading the arguments
i="-i"
v="-v"
s="-s"
e="-e"
d="-d"

###entering new contact
if [ $1 = $i ]
	then
	read -p "Name : " name
	read -p "Phone number : " phone
	echo "$name : $phone" >>$DB
###displaying the phonebook
elif [ $1 = $v ]
	then
	echo "name   phone Number"
	cat "$DB" 
###searching by a name
elif [ $1 = $s ]
	then
	read -p "Name : " name
	grep -i "$name" $DB
###delete all
elif [ $1 = $e ]
	then
	cat /dev/null > $DB
###delete by name
elif [ $1 = $d ]
	then
	read -p "Name : " name
	grep -v "$name" $DB > temp && mv temp $DB
else
	echo '-i create new name and number'
	echo '-v view contacts'
	echo '-s search by name'
	echo '-e Delete all contacts'
	echo '-d Delete by name'

fi
